server:
  port: 8888
spring:
  application:
    name: pagatu-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/USUARIO/Documents/tareamicro/config-repo